# SITE SETTINGS
title: Chronometric Age Extension
navbar:
  left:
  - text: Terms
    menu:
    - text: Darwin Core
      href: https://dwc.tdwg.org/list/
    - text: Chronometric Age
      href: list/
  - text: Guides
    menu:
    - text: Darwin Core Quick Reference
      href: https://dwc.tdwg.org/terms/
    - text: Chronometric Age Quick Reference
      href: terms/
    - text: Text (Darwin Core Archive)
      href: https://dwc.tdwg.org/text/
    - text: RDF
      href: https://dwc.tdwg.org/rdf/
    - text: XML
      href: https://dwc.tdwg.org/xml/
    - text: Questions & Answers
      href: https://github.com/tdwg/dwc-qa/blob/master/README.md
  right:
  - text: GitHub
    href: https://github.com/tdwg/chrono
url: "https://tdwg.github.io"
baseurl: "/chrono"

# SOCIAL PROFILES
social:
  github: tdwg/chrono

# THEME SETTINGS
theme: minima
remote_theme: tdwg/petridish
github_edit: false
logo: /assets/theme/images/tdwg-logo-short.svg

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      path: ""
    values:
      layout: default
      toc: true
