# SITE SETTINGS
title: Chronometric Age Extension
description: Vocabulary maintained by the Darwin Core Maintenance Interest Group to facilitate the sharing of information about chronometric ages and the techniques used to determine them.
# url: "https://chrono.tdwg.org/"
navbar:
  left:
  - text: Terms
    menu:
    - text: Darwin Core
      href: https://dwc.tdwg.org/list/
    - text: Chronometric Age
      href: list/
  - text: Guides
    menu:
    - text: Darwin Core Quick Reference
      href: https://dwc.tdwg.org/terms/
    - text: Chronometric Age Quick Reference
      href: terms/
    - text: Text (Darwin Core Archive)
      href: text/
    - text: RDF
      href: rdf/
    - text: XML
      href: xml/
    - text: Questions & Answers
      href: https://github.com/tdwg/dwc-qa/blob/master/README.md
  right:
  - text: GitHub
    href: https://github.com/tdwg/chrono

# BUILD SETTINGS
markdown: kramdown
remote_theme: tdwg/tdwg-theme-jekyll
plugins:
  - jekyll-feed
